site_name: Angular in IRC
site_url: http://ngirc.js.org
site_description: Compilation of Angular-related resources from the IRC angular channel.
site_author: IRC angular channel community
site_favicon: favicon.ico

repo_url: https://github.com/ngirc/ng-irc

theme: readthedocs
repo_name: GitHub

extra_css:
  - extra/extra.css

extra_javascript:
  - extra/extra.js

pages:
  - 'Home': 'index.md'
  - 'AMA':
    - 'WebReflection 2018-Feb-14': 'ama/webreflection.md'
  - 'AngularJS':
    - 'Resources and links': 'angularjs/resources.md'
    - 'Forms': 'angularjs/forms.md'
    - 'AngularJS Material': 'angularjs/material1.md'
  - 'Angular':
    - 'Resources and links': 'angular/resources.md'
  - 'Javascript': 'javascript.md'
  - 'Reviews': 'reviews.md'
