site_name: Angular in IRC
site_url: http://ngirc.js.org
site_description: Compilation of Angular-related resources from the IRC angular channel.
site_author: IRC angular channel community
site_favicon: favicon.ico

repo_url: https://github.com/ngirc/ng-irc

theme: readthedocs
repo_name: GitHub

extra_javascript:
  - js/extra.js

pages:
  - 'Home': 'index.md'
  - 'Angular 1':
    - 'Resources and links': 'angular1/resources.md'
    - 'Forms': 'angular1/forms.md'
    - 'Material 1': 'angular1/material1.md'
  - 'Angular 2': 'angular2.md'
  - 'Javascript': 'javascript.md'
  - 'Reviews': 'reviews.md'
