site_name: Angular in IRC
site_url: http://ngirc.js.org
site_description: Compilation of Angular-related resources from the IRC angular channel.
site_author: IRC angular channel community
site_favicon: favicon.ico

repo_url: https://github.com/ngirc/ng-irc

theme: readthedocs
repo_name: GitHub

extra_javascript:
- js/extra.js

pages:
  - Angular 1:
    - 'Resources and links': 'angular1/resources.md'
    - 'Forms': 'angular1/forms.md'